name: test CI cache

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.js"

jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v20.12.2

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get XO cache
        uses: actions/cache@v4
        id: xo-cache
        with:
          path: ~/.cache/xo-linter
          key: xo-cache-${{ steps.node.outputs.version }}-${{ hashFiles('**/*.js') }}

      - name: Run xo linter
        run: |
          mkdir -p ~/.cache/xo-linter
          [ -f ~/.cache/xo-linter/xo-cache.json ] && cp ~/.cache/xo-linter/xo-cache.json node_modules/.cache/xo-linter/xo-cache.json || true
          pnpm xo
          cp node_modules/.cache/xo-linter/xo-cache.json ~/.cache/xo-linter/xo-cache.json
        continue-on-error: true
