name: CI cache advance

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.js"

jobs:
  ci:
    name: Running CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v20.12.2

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ steps.node.outputs.version }}

      - name: Install dependencies
        run: npm install

      - name: Run xo linter if JS files changed
        if: steps.node_modules.outputs.cache-hit == 'false'
        run: npm xo
