name: CI with Cache ESLint

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  ci:
    name: Initiate CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install packages
        run: pnpm install

      - name: Restore ESLint Cache
        id: restore-xo-cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/xo-linter
          key: eslint-cache-${{ runner.os }}-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}

      - name: Run Linter
        run: pnpm run lint:eslint
        continue-on-error: true

      - name: Check ESLint cache
        run: head -c 300 ~/.cache/eslint/demo || echo "Cache file not found"
